# Scroll support
set -sg escape-time 0

# Fix Colors
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

# Set the shell
set-option -g default-shell $SHELL

# Color Variable
set -g @BG termina
set -g @FG default
set -g @WINDOW_SELECTED_FG blue
set -g @WINDOW_SELECTED_BG terminal
set -g @SESSION_NAME_FG green
set -g @SESSION_NAME_BG terminal
if-shell "[ -f ~/.config/tmux/theme.conf ]" "source-file ~/.config/tmux/theme.conf"

# Status bar
set -g status-style bg="#{@BG}",fg="#{@FG}"
set -g status-position 'bottom'
set -g status-justify left

bind -n M-Up select-pane -U 
bind -n M-Down select-pane -D 
bind -n M-Left select-pane -L 
bind -n M-Right select-pane -R 

bind -n M-1 select-pane -t 1 
bind -n M-2 select-pane -t 2
bind -n M-3 select-pane -t 3
bind -n M-4 select-pane -t 4
bind -n M-5 select-pane -t 5 

# Set window and pane numbers to start at 1
set -g base-index 1
setw -g pane-base-index 1

# Fix neovim autoread
set -g focus-events on

# Command prompt and message styles
set -g message-style fill=terminal,bg=terminal,fg=default
set -g message-command-style fill=terminal,bg=terminal,fg=default

set-option -g status-left "#[bg=#{@SESSION_NAME_BG},fg=#{@SESSION_NAME_FG},bold] #{session_name} "
set -g window-status-current-format "#[bg=#{@WINDOW_SELECTED_BG},fg=#{@WINDOW_SELECTED_FG},bold] #I:#W "
set -g window-status-format "#[fg=white,bg=default] #I:#W "
set -g status-right "#[fg=default,bg=default,bold] %H:%M "
set -g window-status-separator ""
set -g status-left-length 30
set -g status-right-length 20

# Set pane settings
set -g pane-border-format ""
set -g pane-border-indicators colour
set -g pane-border-style fg=brightblack
set -g pane-active-border-style fg=brightwhite
set -g pane-border-lines single
set -g pane-border-status off


# Set mouse
setw -g mouse on

# Title
set-option -g set-titles on
set-option -g set-titles-string "#S - #W" 

# Bindings
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf
bind c new-window -c "#{pane_current_path}"
bind -n C-S-Left swap-window -t -1\; select-window -t -1
bind -n C-S-Right swap-window -t +1\; select-window -t +1
bind BSpace last-window;

# Line renumbering
set-option -g renumber-windows on

set -g allow-rename off
setw -g mode-keys vi
