#!/bin/zsh

autoload -Uz colors; colors

#### Sources ####

source "$ZDOTDIR/functions.zsh"
source "$ZDOTDIR/alias.zsh"

#### Space Ship Prompt ####

## Linux Settings
if [ $(uname -s) = "Linux" ];then
	zsh_add_plugin "spaceship-prompt/spaceship-prompt"
	autoload -U promptinit; promptinit
	prompt spaceship
fi
SPACESHIP_VI_MODE_SHOW=false
SPACESHIP_USER_SHOW=always

#### Menu Select ####

autoload -Uz compinit
compinit
zstyle ':completion:*' menu select

## Sets default Editor
export EDITOR="nvim"

zsh_add_plugin "zsh-users/zsh-syntax-highlighting"

## Mac Settings
export PATH=/opt/homebrew/bin:$PATH
eval "$(starship init zsh)"
