#!/bin/zsh

autoload -Uz colors; colors
typeset -U path

#### Sources ####

source "$ZDOTDIR/functions.zsh"
source "$ZDOTDIR/alias.zsh"

## Linux Settings
if [ $(uname -s) = "Linux" ];then
	zsh_add_plugin "spaceship-prompt/spaceship-prompt"
	autoload -U promptinit; promptinit
	prompt spaceship
fi
SPACESHIP_VI_MODE_SHOW=false
SPACESHIP_USER_SHOW=always

## Mac Settings

if is_on_mac; then 
fi

#### Menu Select ####

autoload -Uz compinit
compinit
zstyle ':completion:*' menu select

## Sets default Editor
export EDITOR="nvim"

zsh_add_plugin "zsh-users/zsh-syntax-highlighting"

## Mac Settings
export PATH=/opt/homebrew/bin:$PATH

#### Star Ship Prompt ####
eval "$(starship init zsh)"

#### NVM ####
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

#### SSH and GPG ####
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

#### NODE ####
export NODE_OPTIONS=--openssl-legacy-provider

